# Generated by Django 4.0 on 2023-06-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(default='')),
                ('supplier', models.TextField(default='')),
                ('imei', models.BigIntegerField(default=0)),
                ('checked_in_person_name', models.TextField(default='')),
                ('warranty_duration', models.TextField(default='')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
