# Generated by Django 4.0 on 2023-06-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_alter_stock_amount_alter_stock_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='imei',
            field=models.BigIntegerField(default=0),
        ),
    ]
