# Generated by Django 4.0 on 2023-06-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_alter_stock_amount_alter_stock_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='imei',
            field=models.TextField(default=''),
        ),
    ]
