# Generated by Django 4.0 on 2023-06-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stock', '0005_alter_stock_amount_alter_stock_imei'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_damage', models.TextField(default='')),
                ('user_damage_comment', models.TextField(default='')),
                ('amount', models.IntegerField(default=0)),
                ('taken_by', models.TextField(default='')),
                ('taken_date', models.DateField(default='')),
                ('comment', models.TextField(default='')),
                ('issue', models.TextField(default='')),
                ('status', models.TextField(default='')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_center_feedback', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_center_name', models.TextField(default='')),
                ('devices', models.ManyToManyField(default='', to='Service_Center.Device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='service_center_feedback',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='Service_Center.service_feedback'),
        ),
    ]
