# Generated by Django 4.0 on 2023-07-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Center', '0004_alter_device_taken_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_Center',
        ),
    ]
