# Generated by Django 4.0 on 2023-07-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Center', '0005_delete_service_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_center_name', models.TextField(default='')),
                ('devices', models.ManyToManyField(to='Service_Center.Device')),
            ],
        ),
    ]
