# Generated by Django 4.0 on 2023-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stock', '0005_alter_stock_amount_alter_stock_imei'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(default='', max_length=5)),
                ('supplier_name', models.TextField(default='')),
                ('amount', models.IntegerField(default=0)),
                ('number_of_devices', models.IntegerField(default=0)),
                ('PO_number', models.IntegerField(default=0)),
                ('due_date', models.DateField(default='')),
                ('balance', models.IntegerField(default=0)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('pay_this_money_from', models.DateField(default='')),
                ('payment_method', models.TextField(default='')),
                ('cheque_no_or_ref', models.IntegerField(default=0)),
                ('invoice_date', models.DateField(default='')),
                ('invoice_number', models.IntegerField(default=0)),
                ('current_balance', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(to='Stock.Stock')),
            ],
        ),
    ]
