# Generated by Django 4.0 on 2023-06-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='client_pin',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='warranty_status',
        ),
    ]
