# Generated by Django 4.0 on 2023-06-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_remove_sale_client_pin_remove_sale_warranty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_pin',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sale',
            name='warranty_status',
            field=models.TextField(default=''),
        ),
    ]
